version: "3.8"

services:
  ollama-webui:
    container_name: ollama-webui
    hostname: ollama-webui
    image: ghcr.io/open-webui/open-webui:main
    restart: unless-stopped
    ports:
      - 8080
    volumes:
      - /mnt/user/flash_storage/ollama/data:/app/backend/data
      - /mnt/user/flash_storage/ollama/root:/root/.ollama
    environment:
      - OLLAMA_BASE_URL
      - CUSTOM_NAME
      - OPENAI_API_BASE_URLS
      - OPENAI_API_KEYS
    networks:
      - ollama
      - cloud-net
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]


networks:
  ollama:
    external: true

  cloud-net:
    external: true


